theme = "academic"
baseURL = "https://www.glynmottershead.com"
languageCode = "en-uk"
title = "Glyn Mottershead"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "\\.Rproj$", "_files$", "_cache$"]

[params]
        gravatar = "egrommet@gmail.com"
